name: Deploy react app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12.x"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install packages
        run: |
          npm install
          npm run build
      - name: registry github user
        run: |
          git config --global user.email isveth.henao@gmail.com
          git config --global user.name victoria
      - name: deploy the app
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
